name: CI Sécurité Symfony

on:
  push:
    branches: ["main"]

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install dependencies
        run: composer install

      - name: Analyse SAST avec Semgrep
        uses: semgrep/semgrep-action@v1

      - name: Audit des dépendances avec Composer
        run: composer audit

      - name: Symfony Security Check
        run: |
          curl -sSL https://get.symfony.com/cli/installer | bash
          ~/.symfony5/bin/symfony security:check

      - name: Scan DAST avec OWASP ZAP
        run: |
          php -S localhost:8000 -t public/ &
          sleep 5
          docker run --network="host" -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t http://localhost:8000
